name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "main"

jobs:
    tests:
        name: TypeScript Validation
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Admin Validation
              working-directory: admin
              run: npm install && npm run check
