name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "main"

jobs:
    tests:
        name: TypeScript Validation
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Admin
              working-directory: admin
              run: npm run check
