name: Deploy

on:
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy to SVN
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build
              run: ./build.sh

            - name: Deploy to SVN
              env:
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
              run: ./deploy.sh
